### ISSUE TITLE
Error Handling 

### ISSUE THREAD

**Issue by Hermel** [electron-userland/electron-json-storage#130]
Hi,
We are using the API in our app, and we are working now on error handling.
We would like to know if there is a list of all the errors (or at least the most common ones) that the API returns.

**Comment by jviotti** [comment]
Hey there! There are a plethora of errors this module can return, coming from the dependencies we use. The most common ones are I/O errors coming from the `fs` Node.js library. Pretty much any other error you hit is something caused by wrong usage of the library (i.e. setting an invalid data path) or something we should fix!
